export const LOAD_SHOTS_LIST = 'LOAD_SHOTS_LIST';
export const LOAD_SHOT = 'LOAD_SHOT';
export const PAGINATE = 'PAGINATE';
export const SHOW_LARGE_IMAGE = 'SHOW_LARGE_IMAGE';
export const HIDE_LARGE_IMAGE = 'HIDE_LARGE_IMAGE';